apiVersion: v1
kind: Service
metadata:
  name: flask-registration-service
spec:
  type: LoadBalancer
  selector:
    app: flask-registration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
